"""Shared vocabulary. These strings are part of Seaworthy's public output format."""

SCHEMA_VERSION = "1.0"

SEVERITIES = ("CRITICAL", "HIGH", "MEDIUM", "LOW", "INFORMATIONAL")
CONFIDENCES = ("CONFIRMED", "LIKELY", "POTENTIAL", "UNVERIFIED")

CONTROL_STATES = ("VERIFIED", "NOT_MET", "UNVERIFIED", "NOT_APPLICABLE")
COVERAGE_STATES = ("ASSESSED", "NOT_APPLICABLE", "NOT_ASSESSED")
INVENTORY_STATES = ("IDENTIFIED", "NOT_FOUND", "UNVERIFIED")
APPLICABILITY = ("yes", "no", "unknown")

EVIDENCE_KINDS = ("code", "config", "documentation", "dependency", "absence", "user-provided")
LOCATED_EVIDENCE_KINDS = ("code", "config", "documentation", "dependency")

LEGAL_CLASSES = (
    "LEGAL REVIEW REQUIRED",
    "BUSINESS DECISION REQUIRED",
    "POLICY GAP",
    "POLICY/IMPLEMENTATION CONTRADICTION",
    "POTENTIAL LEGAL RISK",
    "INFORMATIONAL",
)
# Classes that send a finding to counsel and therefore need questions for counsel.
LEGAL_CLASSES_NEEDING_QUESTIONS = (
    "LEGAL REVIEW REQUIRED",
    "POLICY/IMPLEMENTATION CONTRADICTION",
    "POTENTIAL LEGAL RISK",
)
LEGAL_STATUSES = (
    "OPEN",
    "LEGAL_REVIEW_REQUESTED",
    "COUNSEL_REVIEWED",
    "DECISION_RECEIVED",
    "IMPLEMENTATION_REQUIRED",
    "IMPLEMENTED",
    "VERIFIED",
    "CLOSED",
)
# Statuses that may only be recorded from information the user supplies.
LEGAL_STATUSES_USER_ONLY = ("COUNSEL_REVIEWED", "DECISION_RECEIVED")

HUMAN_REVIEW_TYPES = ("legal", "security", "privacy", "accessibility", "compliance", "business")

FINDING_STATUSES = (
    "OPEN",
    "REGRESSION",
    "REMEDIATED",
    "VERIFIED",
    "NOT_REPRODUCED",
    "ACCEPTED_RISK",
    "CLOSED",
)
RESOLVED_STATUSES = ("VERIFIED", "CLOSED")

VERIFIER_VERDICTS = ("CONFIRMED", "DOWNGRADED", "REJECTED", "NEEDS_HUMAN")
REMEDIATION_RESULTS = ("FIXED_VERIFIED", "NOT_FIXED", "UNVERIFIED")

GATE_READY = "READY FOR RELEASE"
GATE_READY_ACCEPTED = "READY WITH ACCEPTED RISKS"
GATE_NOT_READY = "NOT READY — REMEDIATION REQUIRED"
GATE_INSUFFICIENT = "BLOCKED — INSUFFICIENT EVIDENCE"
GATE_CRITICAL = "BLOCKED — CRITICAL RISK"
GATES = (GATE_READY, GATE_READY_ACCEPTED, GATE_NOT_READY, GATE_INSUFFICIENT, GATE_CRITICAL)

GATE_EXIT_CODES = {
    GATE_READY: 0,
    GATE_READY_ACCEPTED: 2,
    GATE_NOT_READY: 3,
    GATE_INSUFFICIENT: 4,
    GATE_CRITICAL: 5,
}

SEVERITY_RANK = {s: i for i, s in enumerate(SEVERITIES)}  # lower is more severe
CONTROL_STATE_CAUTION = {"NOT_MET": 3, "UNVERIFIED": 2, "VERIFIED": 1, "NOT_APPLICABLE": 0}

PACKET_DISCLAIMER = (
    "This document is generated by Seaworthy to organize technical findings and questions "
    "for review by qualified legal counsel. It is not legal advice, does not establish legal "
    "compliance, and does not determine the applicability, enforceability, or interpretation "
    "of any law, regulation, contract, or legal requirement."
)

REPORT_DISCLAIMER = (
    "Seaworthy reports evidence it found in the audited scope. It is not legal advice, not a "
    "compliance certification, not an audit opinion, and not a guarantee of security. "
    "\"No finding\" means no evidence of a problem was found in the assessed scope; it does not "
    "mean no problem exists."
)
